### ISSUE TITLE
NPX should always get the latest

### ISSUE THREAD

**Issue by nullfunc** [DefangLabs/defang#472] opened 2024-06-13 21:59 UTC
It's desirable for users to have the latest defang binary. At current if defang is cached (because npx defang ... was previously run) the default behaviour is to use the current installation. This is consistent with the discussion [here](https://github.com/npm/cli/issues/2329).

Users can append @latest (e.g. npx defang@latest ....) to always grab the latest.

We can make changes to
- check against the cached version and download a latest if the cached version is old
- have a way to run against as specific version (i.e. does not download the latest)

**Comment by lionello** [comment] 2024-06-17 21:33
Duplicate of #445

**Closed by lionello** 2024-06-17 21:33 UTC
