### ISSUE TITLE
`defang tail` doesn't show context

### ISSUE THREAD

**Issue by beorn** [DefangLabs/defang#425] opened 2024-05-30 23:08 UTC
When I do `defang tail` the first "saved up" batch of logs that are shown are from 4 days ago, and I only see new logs that happen after I start the tail.  It happens every time.

```
2024-05-26T13:33:01.520743-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178   --> GET / 200 0ms
2024-05-26T13:33:02.809630-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178 sync:worker polling max={blocktime=1000 claimcount=5 claimcount=5}
2024-05-26T13:33:03.515412-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178   <-- GET /
2024-05-26T13:33:03.515554-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178   --> GET / 200 0ms
2024-05-26T13:33:03.856992-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178 sync:worker no work => idling for 30s
2024-05-26T13:33:05.661589-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178 sync:subs:inbound no streams, waiting 10s
2024-05-26T13:33:07.658678-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178   <-- GET /
2024-05-26T13:33:07.658796-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178   --> GET / 200 0ms
2024-05-26T13:33:15.661681-07:00 cucz2h9k0y4m decker-api ip-10-0-82-178 sync:subs:inbound no streams, waiting 10s

2024-05-30T16:05:07.309315-07:00 537674ub21o6 decker-api fabric status=BUILD_PENDING
2024-05-30T16:05:09.642527-07:00 p5cqj6qpfeet decker-api ip-10-0-173-153 @decker/syncsv:worker processTaskQueue max={blockTime=1000 tryReclaims=5 tryClaims=5}
2024-05-30T16:05:10.693258-07:00 p5cqj6qpfeet decker-api ip-10-0-173-153 @decker/syncsv:worker no work => idling for 30s
2024-05-30T16:05:12.855634-07:00 p5cqj6qpfeet decker-api ip-10-0-173-153 @decker/syncsv:subs:inbound no streams, waiting 10s
2024-05-30T16:05:22.862862-07:00 p5cqj6qpfeet decker-api ip-10-0-173-153 @decker/syncsv:subs:inbound no streams, waiting 10s
```

**Comment by lionello** [comment] 2024-06-27 22:46
`tail` should be replaced with something like `docker logs` with optional "follow"

**Comment by lionello** [comment] 2024-08-26 03:26
Duplicate of https://github.com/DefangLabs/defang/issues/459

**Closed by lionello** 2024-08-26 03:26 UTC
