### ISSUE TITLE
Running multiple versions at once

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#122] opened 2024-02-27 04:02 UTC
I just ran into an interesting new issue (or maybe it's expected?). I deployed my app, but it seems like it takes over 6-7 minutes before the new version replaces the old version. I would usually expect a bit of overlap as the first healthchecks pass, but not this long. To be fair, the healthcheck interval is quite high, so maybe it's just that it waits for somewhere between 5-10 healthchecks to pass before removing the old containers?

```
healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 10
```

![CleanShot 2024-02-26 at 19 48 26@2x](https://github.com/defang-io/defang/assets/910895/829bee07-089a-44f0-862d-ed0cbf87cc1d)

**Comment by lionello** [comment] 2024-03-05 18:02
With those parameters, if the service is unhealthy, it would try up to 10*1m = 10m before cycling it. If the service is healthy, it should only have taken ~2m.

**Comment by lionello** [comment] 2024-06-26 20:51
This would be explained better is we had #170 .

**Comment by lionello** [comment] 2024-06-26 20:53
Duplicate of #169

**Closed by lionello** 2024-06-26 20:53 UTC
