### ISSUE TITLE
Deployment says BUILD_QUEUED even though it has failed

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#198] opened 2024-03-14 00:39 UTC

**Comment by lionello** [comment] 2024-03-25 00:46
@raphaeltm was this Playground or BYOC?

**Comment by raphaeltm** [comment] 2024-03-25 01:10
Ah shoot. Sorry, I should have recorded that and provided more context. I can't remember at this point. I think I was doing BYOC videos, though, so I think BYOC?

**Comment by lionello** [comment] 2024-06-26 21:15
Duplicate of #170

**Closed by lionello** 2024-06-26 21:15 UTC
