### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#247] opened 2024-04-04 22:18 UTC
It would be useful to be able to specify multiple domains for a service. There are cases where it might be useful to set some context for an application based on the domain used to access it. Like, I can imagine a dashboard that uses the same app, but modifies some language or visibility of menu items based on the domain:

```
teacher.app.com
```

```
student.app.com
```

Similar but different to #246

**Comment by raphaeltm** [comment] 2024-04-04 22:19
Related to #174

**Comment by lionello** [comment] 2024-06-26 20:15
This also blocks Nounly.

**Comment by lionello** [comment] 2024-07-08 13:06
Blocked by #523

**Comment by Prakash-Sundaresan** [comment] 2024-10-15 22:39
Duplicate of https://github.com/orgs/DefangLabs/projects/4/views/20?pane=issue&itemId=67388462 ?

**Comment by Prakash-Sundaresan** [comment] 2024-10-15 22:42
Duplicate of https://github.com/orgs/DefangLabs/projects/4/views/20?pane=issue&itemId=67388462 ?

**Comment by raphaeltm** [comment] 2024-10-15 22:55
> Duplicate of https://github.com/orgs/DefangLabs/projects/4/views/20?pane=issue&itemId=67388462 ?

My understanding of the spec is that that issue would address internal hostname aliases, not public facing? But @lionello can correct me if I'm wrong.

**Comment by lionello** [comment] 2024-10-16 02:39
Duplicate of https://github.com/DefangLabs/defang-mvp/issues/1108

**Closed by lionello** 2024-10-16 02:39 UTC
Labels: later, networking
